# ============================================================
# model_densenet121.py
# ACML Project — Pneumonia Detection from Chest X-Rays
# Algorithm : DenseNet121 (Transfer Learning)
# ============================================================

# ── 1. Imports ───────────────────────────────────────────────
# type: ignore
import os
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
from tensorflow.keras import Model, layers
from tensorflow.keras.applications import DenseNet121
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import (
    EarlyStopping,
    ModelCheckpoint,
    ReduceLROnPlateau
)
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    auc
)

print("TensorFlow version:", tf.__version__)
print("All libraries imported successfully.")

# ── 2. Configuration ─────────────────────────────────────────
DATA_DIR = os.path.join("chest_xray_processed", "chest_xray_processed")   # generated by preprocess.py

IMG_SIZE   = (224, 224)             # DenseNet121 native input size
BATCH_SIZE = 32
EPOCHS     = 30
SEED       = 42

# Class weights computed by class_weights.py
# Penalise the model more when it misclassifies NORMAL
# because NORMAL is the minority class
CLASS_WEIGHTS = {
    0: 1.8497,   # NORMAL
    1: 0.6852    # PNEUMONIA
}

TRAIN_DIR = os.path.join(DATA_DIR, "train")
VAL_DIR   = os.path.join(DATA_DIR, "val")
TEST_DIR  = os.path.join(DATA_DIR, "test")

OUTPUT_DIR = "outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("Configuration set.")
print(f"  Training data:   {TRAIN_DIR}")
print(f"  Validation data: {VAL_DIR}")
print(f"  Test data:       {TEST_DIR}")

# ── 3. Data Generators ───────────────────────────────────────
# DenseNet121 was pre-trained on ImageNet, so we normalise
# using ImageNet mean/std instead of a plain /255 rescale.
# This ensures the pixel distributions match what the frozen
# convolutional layers expect.
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

def imagenet_preprocess(img):
    img = img / 255.0
    img = (img - IMAGENET_MEAN) / IMAGENET_STD
    return img

train_datagen = ImageDataGenerator(
    preprocessing_function=imagenet_preprocess,
    rotation_range=10,
    width_shift_range=0.05,
    height_shift_range=0.05,
    zoom_range=0.1,
    horizontal_flip=True,
)

val_test_datagen = ImageDataGenerator(
    preprocessing_function=imagenet_preprocess   # no augmentation on val/test
)

train_gen = train_datagen.flow_from_directory(
    TRAIN_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="binary",     # binary: NORMAL=0, PNEUMONIA=1 (alphabetical)
    color_mode="rgb",
    seed=SEED
)

val_gen = val_test_datagen.flow_from_directory(
    VAL_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="binary",
    color_mode="rgb",
    seed=SEED
)

test_gen = val_test_datagen.flow_from_directory(
    TEST_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="binary",
    color_mode="rgb",
    shuffle=False,           # IMPORTANT: keep order for evaluation
    seed=SEED
)

print("\nData loaded successfully.")
print(f"  Training samples:   {train_gen.samples}")
print(f"  Validation samples: {val_gen.samples}")
print(f"  Test samples:       {test_gen.samples}")
print(f"  Class indices:      {train_gen.class_indices}")

# ── 4. Model Definition ──────────────────────────────────────
def build_densenet121():
    """
    Two-phase transfer learning with DenseNet121:

    Phase 1 — Feature extraction:
        The entire DenseNet121 base is frozen. Only the new
        classification head is trained. This is cheap and prevents
        corrupting pre-trained weights before the head is stable.

    Phase 2 — Fine-tuning:
        The last dense block (~50 layers) is unfrozen and trained
        at a very low learning rate so the model can adapt its
        higher-level feature detectors to chest X-ray textures
        without forgetting general ImageNet features.
    """
    # Load DenseNet121 pre-trained on ImageNet, remove its classifier top
    base_model = DenseNet121(
        weights="imagenet",
        include_top=False,           # drop the 1000-class head
        input_shape=(224, 224, 3)
    )
    base_model.trainable = False     # freeze for Phase 1

    # Build the classification head on top
    inputs = tf.keras.Input(shape=(224, 224, 3))
    x = base_model(inputs, training=False)  # training=False keeps BN layers frozen
    x = layers.GlobalAveragePooling2D()(x)  # collapse spatial dims → 1D vector
    x = layers.BatchNormalization()(x)
    x = layers.Dense(256, activation="relu")(x)
    x = layers.Dropout(0.5)(x)              # regularisation
    outputs = layers.Dense(1, activation="sigmoid")(x)  # probability for PNEUMONIA

    model = Model(inputs, outputs)
    return model, base_model


model, base_model = build_densenet121()

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

# ── 5. Phase 1 — Feature Extraction ─────────────────────────
print("=" * 50)
print("PHASE 1: Feature Extraction  (base frozen, LR=1e-3)")
print("=" * 50)

callbacks_phase1 = [
    EarlyStopping(
        monitor="val_loss",
        patience=5,
        restore_best_weights=True,
        verbose=1
    ),
    ModelCheckpoint(
        filepath=os.path.join(OUTPUT_DIR, "best_densenet121_phase1.keras"),
        monitor="val_loss",
        save_best_only=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=3,
        verbose=1
    )
]

history_phase1 = model.fit(
    train_gen,
    epochs=10,                  # head converges quickly; 10 is enough
    validation_data=val_gen,
    class_weight=CLASS_WEIGHTS,
    callbacks=callbacks_phase1
)

print("\nPhase 1 complete.")

# ── 6. Phase 2 — Fine-tuning ─────────────────────────────────
print("=" * 50)
print("PHASE 2: Fine-tuning  (top layers unfrozen, LR=1e-5)")
print("=" * 50)

base_model.trainable = True

total_layers   = len(base_model.layers)
FINE_TUNE_FROM = total_layers - 50       # keep early layers frozen

for layer in base_model.layers[:FINE_TUNE_FROM]:
    layer.trainable = False

print(f"  Total base layers  : {total_layers}")
print(f"  Frozen up to layer : {FINE_TUNE_FROM}")
print(f"  Trainable layers   : {sum(1 for l in base_model.layers if l.trainable)}")

# Very low LR — avoids destroying the pre-trained weights
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

callbacks_phase2 = [
    EarlyStopping(
        monitor="val_loss",
        patience=5,
        restore_best_weights=True,
        verbose=1
    ),
    ModelCheckpoint(
        filepath=os.path.join(OUTPUT_DIR, "best_densenet121_phase2.keras"),
        monitor="val_loss",
        save_best_only=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=3,
        verbose=1
    )
]

history_phase2 = model.fit(
    train_gen,
    epochs=EPOCHS,
    validation_data=val_gen,
    class_weight=CLASS_WEIGHTS,
    callbacks=callbacks_phase2
)

print("\nPhase 2 complete.")

# ── 7. Training History Plot ─────────────────────────────────
# Merge both phases into one continuous curve
combined = {
    key: history_phase1.history[key] + history_phase2.history[key]
    for key in history_phase1.history
}
phase1_len = len(history_phase1.history["loss"])

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("DenseNet121 — Training History", fontsize=14, fontweight="bold")

for ax, (train_key, val_key), ylabel in zip(
    axes,
    [("accuracy", "val_accuracy"), ("loss", "val_loss")],
    ["Accuracy", "Loss"]
):
    ep = range(1, len(combined[train_key]) + 1)
    ax.plot(ep, combined[train_key], label=f"Training {ylabel}")
    ax.plot(ep, combined[val_key],   label=f"Validation {ylabel}")
    ax.axvline(x=phase1_len, color="gray", linestyle="--", label="Fine-tuning starts")
    ax.set_title(f"Model {ylabel} over Epochs")
    ax.set_xlabel("Epoch")
    ax.set_ylabel(ylabel)
    ax.legend()
    ax.grid(True)

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "training_history_densenet121.png"), dpi=150)
plt.show()
print("✅ Training history saved to outputs/training_history_densenet121.png")

# ── 8. Evaluation on Test Set ────────────────────────────────
print("=" * 50)
print("EVALUATING ON TEST SET")
print("=" * 50)

y_true      = test_gen.classes
y_pred_prob = model.predict(test_gen, verbose=1).flatten()
y_pred      = (y_pred_prob > 0.5).astype(int)

accuracy = np.mean(y_true == y_pred)
print(f"\nAccuracy: {accuracy:.4f} ({accuracy * 100:.2f}%)")

print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=["NORMAL", "PNEUMONIA"]))

# ── 9. Confusion Matrix ──────────────────────────────────────
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["NORMAL", "PNEUMONIA"],
    yticklabels=["NORMAL", "PNEUMONIA"]
)
plt.title("Confusion Matrix — DenseNet121", fontsize=14, fontweight="bold")
plt.ylabel("True Label")
plt.xlabel("Predicted Label")
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "confusion_matrix_densenet121.png"), dpi=150)
plt.show()
print("✅ Confusion matrix saved to outputs/confusion_matrix_densenet121.png")

# ── 10. ROC Curve ────────────────────────────────────────────
fpr, tpr, _ = roc_curve(y_true, y_pred_prob)
roc_auc     = auc(fpr, tpr)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color="darkorange", lw=2,
         label=f"ROC Curve (AUC = {roc_auc:.4f})")
plt.plot([0, 1], [0, 1], color="navy", lw=2, linestyle="--",
         label="Random Classifier")
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve — DenseNet121", fontsize=14, fontweight="bold")
plt.legend(loc="lower right")
plt.grid(True)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "roc_curve_densenet121.png"), dpi=150)
plt.show()
print(f"✅ ROC curve saved to outputs/roc_curve_densenet121.png  |  AUC = {roc_auc:.4f}")

# ── 11. Save Final Model ─────────────────────────────────────
model.save(os.path.join(OUTPUT_DIR, "final_densenet121.keras"))
print("\n✅ Final model saved to outputs/final_densenet121.keras")